### ISSUE TITLE
Suggestion: Drop support for python < 3.7

### ISSUE THREAD

**Issue by aqeelat** [riga/order#20]
I would like to work on this task

**Comment by riga** [comment]
Hi @aqeelat ,

Thanks for opening an issue!
Can you elaborate on the motivation for dropping the support?

**Comment by riga** [comment]
Hi @aqeelat ,

Thanks for opening in issue! Can you elaborate why you would like to drop the support?

**Comment by aqeelat** [comment]
@riga because these versions reached EOL a while ago. Also, removing them will make the code more maintainable and allow for using new python features.

**Comment by riga** [comment]
The package is used in a scientific context where we, unfortunately, need to provide support exceeding the usual EOL spans (e.g. CentOS7 which is still mostly used at CERN comes with 3.6).
